### ISSUE TITLE
Authentication for Users to Take the Polls

### ISSUE THREAD

**Issue by khinezarthwe** [khinezarthwe/mmdt_web_app#33]
- Utilize Django's built-in authentication system when user takes the poll

**Comment by khinezar-mercari** [comment]
I would like to recommend doing this first before addressing this issue: https://github.com/khinezarthwe/mmdt_web_app/issues/36.

We will offer two options for taking polls on our website:

- [ ] Anonymous Polls: Users can vote on polls without logging in.
- [ ] Registered Polls: Users can vote on polls when they are logged in.

Admin Functionality:

- [ ] The admin can manage the poll vote options in the admin panel.
