### ISSUE TITLE
Adding  Survey Feature 

### ISSUE THREAD

**Issue by khinezarthwe** [khinezarthwe/mmdt_web_app#39]
### **Surveys**

1. **Prepare the DB Structure and Backend**:
    - Design models to store survey questions, options, and responses.
    - Use Django ORM for database interactions.
2. **UI for Survey Data Collections**:
    - Create intuitive forms for data input.
    - Validate data on both frontend and backend.

**Comment by khinezarthwe** [comment]
@YoutLone Let's start this one when we finish poll-related tasks.

**Comment by YoutLone** [comment]
Okay  sis @khinezarthwe .

**Comment by khinezarthwe** [comment]
@YoutLone  @Pyae24  Please work together on DB Structure  data structure. 
Before implementation
- [ ] Decide the DB structure and mockup first before implementation 
- [ ] Create sample mockup for UI
