### ISSUE TITLE
Implement Pagination in UI to Display All Polls from Database

### ISSUE THREAD

**Issue by khinezarthwe** [khinezarthwe/mmdt_web_app#41]
Description:
Currently, our application is set up to retrieve and display only the latest 5 polls from the database. However, as the number of polls grows, this limitation restricts our ability to view older polls. To enhance user experience and provide access to all available polls, I propose implementing pagination in the UI.

Suggested Implementation:

- [ ] Modify the backend to support pagination. It should be able to send a specified number of polls per request (e.g., 5 polls per page).
- [ ] Update the frontend to include pagination controls, allowing users to navigate through different pages.

**Comment by phyodev** [comment]
[https://github.com/khinezarthwe/mmdt_web_app/pull/51](url)

**Comment by phyodev** [comment]
d018a7583a35dd84c046b53d4baa7e4c5f1d910a

**Comment by phyodev** [comment]
[d018a7583a35dd84c046b53d4baa7e4c5f1d910a](url)
