### ISSUE TITLE
Bug [comment submit button] do not work

### ISSUE THREAD

**Issue by khinezarthwe** [khinezarthwe/mmdt_web_app#42]
The error occurs when a user clicks the 'Submit Comment' button.
It is unclear whether the issue lies in the frontend UI handling or the backend processing of the comment data.

- [ ] Investigate the error logs to identify the specific nature of the issue.
- [ ] Check the frontend code for any event handling or data submission errors.
- [ ] Review the backend API for handling comment submissions, ensuring it processes requests correctly.
- [ ] Test the comment submission process in different scenarios (e.g., with different user accounts, different browsers) to replicate and understand the issue.

Comment BOX: 
<img width="1379" alt="Screenshot 2023-12-28 at 9 22 09 PM" src="https://github.com/khinezarthwe/mmdt_web_app/assets/5201124/8920cd5b-0d0b-4b2e-be2e-b6c13fabaa44">

Current Error Page
<img width="1244" alt="Screenshot 2023-12-28 at 9 25 35 PM" src="https://github.com/khinezarthwe/mmdt_web_app/assets/5201124/a4b4c54d-5f9f-4af7-a933-44ae90e15f86">

**Comment by thetpainglin** [comment]
This is the problem with calling the backend api. The reason is that you get an error after submitting.
By looking at the 405 status code, there is often a problem with adding data to the get method.
